import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/src/context/AuthContext";

import "./globals.css";
import { CartProvider } from "../context/CartContext";
import { I18NProvider } from "next/dist/server/lib/i18n-provider";
import { I18nProvider } from "../context/i18nContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <I18nProvider>
          <AuthProvider>
          <CartProvider>
        {children}
          </CartProvider>
        </AuthProvider>
        </I18nProvider>
        
        </body>
    </html>
  );
}
